# Generated by Django 4.2.9 on 2024-01-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(choices=[(1, 'Mangaer'), (2, 'Delivery Crew'), (3, 'User')], default=3),
        ),
    ]
